/**
 * Module: harness configuration governance.
 * Spec component: "Harness configuration governance — drift prevention across
 * harness instruction surfaces (CLAUDE.md, AGENTS.md, .cursor rules): one
 * canonical source (`.ade/instructions.md`) rendered into hash-guarded
 * managed blocks, with hand-edits inside the markers refused rather than
 * silently clobbered."
 * Boundary controlled: the config boundary (canonical instructions vs.
 * per-harness generated surfaces).
 */
import { join } from "node:path";
import { readIfExists } from "../fsutil.ts";
import { INSTRUCTIONS_PATH } from "../instructions.ts";
import { extractManagedBlock } from "../managed.ts";
import { translationTargets } from "../translate.ts";
import { readJson, verifyJsonArtifact, writePolicy } from "./_shared.ts";
import type { AdeModule, Ctx, Finding, PlannedAction } from "../types.ts";

export const GOVERNANCE_POLICY_PATH = ".ade/policy/instructions-governance.json";

interface GovernancePolicy {
  schemaVersion: number;
  canonicalSource: string;
  managedFiles: Array<{ path: string; harnesses: string[] }>;
  driftPolicy: string;
  ownership: string;
}

function buildPolicy(ctx: Ctx): GovernancePolicy {
  return {
    schemaVersion: 1,
    canonicalSource: INSTRUCTIONS_PATH,
    managedFiles: translationTargets(ctx.config.harnesses).map((target) => ({
      path: target.path,
      harnesses: target.harnesses,
    })),
    driftPolicy:
      "managed blocks are regenerated by ade translate; hand-edits inside markers are refused",
    ownership: "content outside ade markers is user-owned and never touched",
  };
}

export const configGovernanceModule: AdeModule = {
  id: "config-governance",
  title: "Harness Configuration Governance",
  category: "governance",
  spec: "Harness configuration governance",
  defaultEnabled: true,
  instructionBlocks: [
    {
      id: "config-governance",
      title: "Harness Configuration Governance",
      content: [
        "`.ade/instructions.md` is the single source of truth for harness instructions.",
        "- Edit `.ade/instructions.md` — never the generated blocks in CLAUDE.md / AGENTS.md / .cursor rules — then run `ade translate`.",
        "- Generated blocks carry a content-hash; hand-edits inside the ade markers are detected and refused.",
        "- Content outside the ade markers is user-owned and is never touched by ADE.",
      ].join("\n"),
    },
  ],

  async detect(ctx: Ctx): Promise<Finding[]> {
    const targets = translationTargets(ctx.config.harnesses);
    if (targets.length === 0) {
      return [
        {
          level: "warn",
          message: "no configured harnesses resolve to an instruction file — nothing to govern",
          remediation: "add harness ids to `harnesses` in ade.json",
        },
      ];
    }
    return [
      {
        level: "ok",
        message: `governing ${targets.length} instruction file(s): ${targets.map((target) => target.path).join(", ")}`,
      },
    ];
  },

  async plan(ctx: Ctx): Promise<PlannedAction[]> {
    void ctx;
    return [
      {
        kind: "write" as const,
        path: GOVERNANCE_POLICY_PATH,
        description:
          "write instructions-governance policy (canonical source, managed files, drift + ownership rules)",
      },
    ];
  },

  async apply(ctx: Ctx) {
    await writePolicy(ctx, GOVERNANCE_POLICY_PATH, buildPolicy(ctx));
    return {
      status: "applied" as const,
      findings: [{ level: "ok" as const, message: `wrote ${GOVERNANCE_POLICY_PATH}` }],
      wrotePaths: [GOVERNANCE_POLICY_PATH],
    };
  },

  async verify(ctx: Ctx) {
    const findings: Finding[] = [];

    const canonical = await readIfExists(join(ctx.targetDir, INSTRUCTIONS_PATH));
    if (canonical === null) {
      findings.push({
        level: "error",
        message: `canonical instruction source missing: ${INSTRUCTIONS_PATH}`,
        remediation: "run `ade apply` to regenerate the canonical instructions",
      });
    } else {
      findings.push({ level: "ok", message: `${INSTRUCTIONS_PATH} present` });
    }

    for (const target of translationTargets(ctx.config.harnesses)) {
      const existing = await readIfExists(join(ctx.targetDir, target.path));
      if (existing === null) {
        findings.push({
          level: "error",
          message: `instruction file missing: ${target.path}`,
          remediation: "run `ade translate`",
        });
        continue;
      }
      if (extractManagedBlock(existing) === null) {
        findings.push({
          level: "error",
          message: `managed block missing or corrupt in ${target.path}`,
          remediation: "run `ade translate`",
        });
        continue;
      }
      findings.push({ level: "ok", message: `${target.path} carries an intact managed block` });
    }

    findings.push(await verifyJsonArtifact(ctx, GOVERNANCE_POLICY_PATH));
    const policy = (await readJson(ctx, GOVERNANCE_POLICY_PATH)) as GovernancePolicy | null;
    if (policy !== null && policy.canonicalSource !== INSTRUCTIONS_PATH) {
      findings.push({
        level: "error",
        message: `${GOVERNANCE_POLICY_PATH} names an unexpected canonical source`,
        remediation: "run `ade apply` to regenerate",
      });
    }

    const ok = findings.every((finding) => finding.level !== "error");
    return { ok, findings };
  },
};
