//! Module: harness configuration governance.
//! Port of `src/modules/config-governance.ts`.
//!
//! Spec component: "Harness configuration governance — drift prevention across
//! harness instruction surfaces (CLAUDE.md, AGENTS.md, .cursor rules): one
//! canonical source (`.ade/instructions.md`) rendered into hash-guarded
//! managed blocks, with hand-edits inside the markers refused rather than
//! silently clobbered."
//! Boundary controlled: the config boundary (canonical instructions vs.
//! per-harness generated surfaces).

use crate::fsutil::read_if_exists;
use crate::instructions::INSTRUCTIONS_PATH;
use crate::managed::extract_managed_block;
use crate::modules::shared::{read_json, verify_json_artifact, write_policy};
use crate::translate::translation_targets;
use crate::types::{
    ActionKind, AdeModule, Ctx, Finding, FindingLevel, InstructionBlock, ModuleResult,
    ModuleStatus, PlannedAction, VerifyResult,
};

pub const GOVERNANCE_POLICY_PATH: &str = ".ade/policy/instructions-governance.json";

fn build_policy(ctx: &Ctx) -> serde_json::Value {
    let managed_files: Vec<serde_json::Value> = translation_targets(&ctx.config.harnesses)
        .into_iter()
        .map(|target| serde_json::json!({ "path": target.path, "harnesses": target.harnesses }))
        .collect();
    serde_json::json!({
        "schemaVersion": 1,
        "canonicalSource": INSTRUCTIONS_PATH,
        "managedFiles": managed_files,
        "driftPolicy":
            "managed blocks are regenerated by ade translate; hand-edits inside markers are refused",
        "ownership": "content outside ade markers is user-owned and never touched",
    })
}

pub struct ConfigGovernanceModule;

pub static MODULE: ConfigGovernanceModule = ConfigGovernanceModule;

fn apply_inner(ctx: &Ctx) -> std::io::Result<ModuleResult> {
    write_policy(ctx, GOVERNANCE_POLICY_PATH, &build_policy(ctx))?;
    Ok(ModuleResult {
        status: ModuleStatus::Applied,
        findings: vec![Finding::ok(format!("wrote {GOVERNANCE_POLICY_PATH}"))],
        wrote_paths: vec![GOVERNANCE_POLICY_PATH.to_string()],
    })
}

impl AdeModule for ConfigGovernanceModule {
    fn id(&self) -> &'static str {
        "config-governance"
    }
    fn title(&self) -> &'static str {
        "Harness Configuration Governance"
    }
    fn category(&self) -> &'static str {
        "governance"
    }
    fn spec(&self) -> &'static str {
        "Harness configuration governance"
    }

    fn instruction_blocks(&self) -> Vec<InstructionBlock> {
        vec![InstructionBlock {
            id: "config-governance",
            title: "Harness Configuration Governance",
            content: [
                "`.ade/instructions.md` is the single source of truth for harness instructions.",
                "- Edit `.ade/instructions.md` — never the generated blocks in CLAUDE.md / AGENTS.md / .cursor rules — then run `ade translate`.",
                "- Generated blocks carry a content-hash; hand-edits inside the ade markers are detected and refused.",
                "- Content outside the ade markers is user-owned and is never touched by ADE.",
            ]
            .join("\n"),
        }]
    }

    fn detect(&self, ctx: &Ctx) -> Vec<Finding> {
        let targets = translation_targets(&ctx.config.harnesses);
        if targets.is_empty() {
            return vec![Finding::warn(
                "no configured harnesses resolve to an instruction file — nothing to govern",
                "add harness ids to `harnesses` in ade.json",
            )];
        }
        let paths: Vec<&str> = targets.iter().map(|target| target.path).collect();
        vec![Finding::ok(format!(
            "governing {} instruction file(s): {}",
            targets.len(),
            paths.join(", ")
        ))]
    }

    fn plan(&self, _ctx: &Ctx) -> Vec<PlannedAction> {
        vec![PlannedAction {
            kind: ActionKind::Write,
            path: Some(GOVERNANCE_POLICY_PATH.to_string()),
            description:
                "write instructions-governance policy (canonical source, managed files, drift + ownership rules)"
                    .to_string(),
        }]
    }

    fn apply(&self, ctx: &Ctx) -> ModuleResult {
        match apply_inner(ctx) {
            Ok(result) => result,
            Err(err) => ModuleResult {
                status: ModuleStatus::Failed,
                findings: vec![Finding::error(format!("module threw: {err}"))],
                wrote_paths: vec![],
            },
        }
    }

    fn verify(&self, ctx: &Ctx) -> VerifyResult {
        let mut findings: Vec<Finding> = Vec::new();

        let canonical = read_if_exists(&ctx.target_dir.join(INSTRUCTIONS_PATH));
        match canonical {
            None => findings.push(Finding::error_with(
                format!("canonical instruction source missing: {INSTRUCTIONS_PATH}"),
                "run `ade apply` to regenerate the canonical instructions",
            )),
            Some(_) => findings.push(Finding::ok(format!("{INSTRUCTIONS_PATH} present"))),
        }

        for target in translation_targets(&ctx.config.harnesses) {
            let existing = read_if_exists(&ctx.target_dir.join(target.path));
            let Some(existing) = existing else {
                findings.push(Finding::error_with(
                    format!("instruction file missing: {}", target.path),
                    "run `ade translate`",
                ));
                continue;
            };
            if extract_managed_block(&existing).is_none() {
                findings.push(Finding::error_with(
                    format!("managed block missing or corrupt in {}", target.path),
                    "run `ade translate`",
                ));
                continue;
            }
            findings.push(Finding::ok(format!(
                "{} carries an intact managed block",
                target.path
            )));
        }

        findings.push(verify_json_artifact(ctx, GOVERNANCE_POLICY_PATH));
        if let Some(policy) = read_json(ctx, GOVERNANCE_POLICY_PATH) {
            let canonical_source = policy
                .get("canonicalSource")
                .and_then(|value| value.as_str());
            if canonical_source != Some(INSTRUCTIONS_PATH) {
                findings.push(Finding::error_with(
                    format!("{GOVERNANCE_POLICY_PATH} names an unexpected canonical source"),
                    "run `ade apply` to regenerate",
                ));
            }
        }

        let ok = findings
            .iter()
            .all(|finding| finding.level != FindingLevel::Error);
        VerifyResult { ok, findings }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fsutil::sha256_hex;
    use crate::managed::{upsert_managed_block, UpsertResult};
    use crate::testutil::{make_temp_dir, make_test_ctx, test_config_with, TestCtxOptions};
    use std::path::Path;

    const CANONICAL_BODY: &str = "# ADE Baseline Instructions\n\n- Follow the ADE baseline.\n";

    /// Seed the canonical source + translated instruction files for claude-code + codex.
    fn seed_translated_fixture(dir: &Path) {
        let canonical = dir.join(".ade").join("instructions.md");
        std::fs::create_dir_all(canonical.parent().unwrap()).unwrap();
        std::fs::write(&canonical, CANONICAL_BODY).unwrap();
        for rel in ["CLAUDE.md", "AGENTS.md"] {
            let UpsertResult::Ok { content, .. } = upsert_managed_block("", CANONICAL_BODY) else {
                panic!("upsert failed");
            };
            std::fs::write(dir.join(rel), content).unwrap();
        }
    }

    fn read_file(dir: &Path, rel: &str) -> String {
        std::fs::read_to_string(dir.join(rel)).expect("read file")
    }

    fn ctx_for(dir: &Path, harnesses: &[&str]) -> crate::types::Ctx {
        make_test_ctx(
            dir,
            TestCtxOptions {
                config: Some(test_config_with(&[], harnesses)),
                ..Default::default()
            },
        )
    }

    #[test]
    fn isc_58_apply_writes_governance_policy_with_canonical_source_managed_files_and_rules() {
        let dir = make_temp_dir("cg-policy");
        let ctx = ctx_for(&dir, &["claude-code", "codex"]);
        let result = MODULE.apply(&ctx);
        assert_eq!(result.status, ModuleStatus::Applied);
        assert!(result
            .wrote_paths
            .contains(&GOVERNANCE_POLICY_PATH.to_string()));

        let policy: serde_json::Value =
            serde_json::from_str(&read_file(&dir, GOVERNANCE_POLICY_PATH)).unwrap();
        assert_eq!(policy["canonicalSource"], ".ade/instructions.md");
        assert_eq!(
            policy["managedFiles"],
            serde_json::json!([
                { "harnesses": ["codex"], "path": "AGENTS.md" },
                { "harnesses": ["claude-code"], "path": "CLAUDE.md" }
            ])
        );
        let drift = policy["driftPolicy"].as_str().unwrap();
        assert!(drift.contains("ade translate"));
        assert!(drift.contains("refused"));
        assert!(policy["ownership"].as_str().unwrap().contains("user-owned"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn isc_58_managed_files_dedupe_shared_agents_md_across_harnesses() {
        let dir = make_temp_dir("cg-dedupe");
        let ctx = ctx_for(&dir, &["codex", "opencode"]);
        MODULE.apply(&ctx);
        let policy: serde_json::Value =
            serde_json::from_str(&read_file(&dir, GOVERNANCE_POLICY_PATH)).unwrap();
        assert_eq!(
            policy["managedFiles"],
            serde_json::json!([{ "harnesses": ["codex", "opencode"], "path": "AGENTS.md" }])
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn isc_116_plan_writes_nothing_to_disk() {
        let dir = make_temp_dir("cg-plan");
        let ctx = make_test_ctx(&dir, TestCtxOptions::default());
        let actions = MODULE.plan(&ctx);
        assert!(!actions.is_empty());
        assert_eq!(actions[0].path.as_deref(), Some(GOVERNANCE_POLICY_PATH));
        assert!(!dir.join(GOVERNANCE_POLICY_PATH).exists());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn isc_117_apply_is_idempotent_second_run_byte_identical() {
        let dir = make_temp_dir("cg-idem");
        MODULE.apply(&make_test_ctx(&dir, TestCtxOptions::default()));
        let first = sha256_hex(&read_file(&dir, GOVERNANCE_POLICY_PATH));
        MODULE.apply(&make_test_ctx(&dir, TestCtxOptions::default()));
        let second = sha256_hex(&read_file(&dir, GOVERNANCE_POLICY_PATH));
        assert_eq!(second, first);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn verify_passes_on_a_fully_translated_repo() {
        let dir = make_temp_dir("cg-verify-ok");
        let ctx = ctx_for(&dir, &["claude-code", "codex"]);
        seed_translated_fixture(&dir);
        MODULE.apply(&ctx);
        let result = MODULE.verify(&ctx);
        assert!(result.ok);
        assert!(result
            .findings
            .iter()
            .all(|finding| finding.level == FindingLevel::Ok));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn verify_fails_naming_agents_md_when_it_is_deleted_with_translate_remediation() {
        let dir = make_temp_dir("cg-missing");
        let ctx = ctx_for(&dir, &["claude-code", "codex"]);
        seed_translated_fixture(&dir);
        MODULE.apply(&ctx);
        std::fs::remove_file(dir.join("AGENTS.md")).unwrap();
        let result = MODULE.verify(&ctx);
        assert!(!result.ok);
        let missing = result
            .findings
            .iter()
            .find(|finding| {
                finding.level == FindingLevel::Error && finding.message.contains("AGENTS.md")
            })
            .expect("missing-file finding");
        assert!(missing
            .remediation
            .as_deref()
            .unwrap()
            .contains("ade translate"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn verify_fails_naming_claude_md_when_its_managed_markers_are_corrupted() {
        let dir = make_temp_dir("cg-corrupt");
        let ctx = ctx_for(&dir, &["claude-code", "codex"]);
        seed_translated_fixture(&dir);
        MODULE.apply(&ctx);
        let claude_md = read_file(&dir, "CLAUDE.md");
        std::fs::write(
            dir.join("CLAUDE.md"),
            format!("{claude_md}\n<!-- ade:begin -->\n"),
        )
        .unwrap();
        let result = MODULE.verify(&ctx);
        assert!(!result.ok);
        let corrupt = result
            .findings
            .iter()
            .find(|finding| {
                finding.level == FindingLevel::Error && finding.message.contains("CLAUDE.md")
            })
            .expect("corrupt-markers finding");
        assert!(corrupt.message.contains("managed block"));
        assert!(corrupt
            .remediation
            .as_deref()
            .unwrap()
            .contains("ade translate"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn verify_fails_when_the_canonical_instructions_file_is_missing() {
        let dir = make_temp_dir("cg-nocanon");
        let ctx = ctx_for(&dir, &["claude-code", "codex"]);
        seed_translated_fixture(&dir);
        MODULE.apply(&ctx);
        std::fs::remove_file(dir.join(".ade").join("instructions.md")).unwrap();
        let result = MODULE.verify(&ctx);
        assert!(!result.ok);
        assert!(result.findings.iter().any(|finding| {
            finding.level == FindingLevel::Error && finding.message.contains(".ade/instructions.md")
        }));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn verify_fails_when_the_governance_policy_artifact_is_missing_or_corrupt() {
        let dir = make_temp_dir("cg-nopolicy");
        let ctx = ctx_for(&dir, &["claude-code", "codex"]);
        seed_translated_fixture(&dir);
        // Never applied → policy artifact absent.
        assert!(!MODULE.verify(&ctx).ok);

        MODULE.apply(&ctx);
        std::fs::write(dir.join(GOVERNANCE_POLICY_PATH), "{not json").unwrap();
        assert!(!MODULE.verify(&ctx).ok);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn instruction_block_names_the_canonical_source_and_the_translate_workflow() {
        let blocks = MODULE.instruction_blocks();
        assert!(!blocks.is_empty());
        let block = &blocks[0];
        assert!(block.content.contains(".ade/instructions.md"));
        assert!(block.content.contains("ade translate"));
        assert!(block.content.contains("content-hash"));
    }

    #[test]
    fn detect_reports_governed_files_and_warns_when_no_harness_resolves() {
        let dir = make_temp_dir("cg-detect");
        let ok = MODULE.detect(&ctx_for(&dir, &["claude-code", "codex"]));
        assert!(ok.iter().any(|finding| {
            finding.level == FindingLevel::Ok && finding.message.contains("CLAUDE.md")
        }));
        let none = MODULE.detect(&ctx_for(&dir, &[]));
        assert!(none
            .iter()
            .any(|finding| finding.level == FindingLevel::Warn));
        let _ = std::fs::remove_dir_all(&dir);
    }
}
